
library(data.table)
library(argparse)
library(dplyr)
library(MOSAIC)
"%&%" = function(a,b) paste(a,b,sep="")

parser <- ArgumentParser()
parser$add_argument("--rdata", help="Rdata object ouput by MOSAIC")
parser$add_argument("--intermediate", help="path to intermediate folder generated by mosaic wrapper containing inputs of mosaic run")
parser$add_argument("--haps.sample", help="admixed samle list as in MOSAIC intermediate files")
parser$add_argument("--nancestries", help="number of ancestries")
parser$add_argument("--result", help="results file output by adsimr")
parser$add_argument("--bim", help="admixed bim file")
parser$add_argument("--out", help="file you would like to output as")
args <- parser$parse_args()



#Read in snp ids
print("processing snp ids")
bim<-fread(args$bim, header = F, drop = c("V2", "V3","V5","V6"))
dim(bim)
colnames(bim)<-c("chm","pos")

#read in true ancestry and keep only snps found in bim file
print("reading in  true ancestry")
res<-as.data.frame(fread(args$result,header = T, showProgress = T))
res<-inner_join(bim,res,by=c("chm","pos"))

##read in and convert MOSAIC grid to snp level ancestries
print("Processing MOSAIC ancestry")
load(args$rdata)
local_pos=grid_to_pos(localanc,args$intermediate,g.loc,chrnos=22)

print("calculating haploid accuracy")
hap_cor<-c(rep(NA,40))
#create two empty data frames to fill with diploid ancestries
diploid_true<-data.frame(matrix(ncol = 20,nrow=50000))
local_df<-data.frame(matrix(ncol = 20,nrow=50000))
#convert haploid ancestries to diploid ancestries

if (args$nancestries == 3){
  random<-c(1,2,3)
  for ( i in c(1:20)){ 
    cat( i, "/20\n")
    hap2<-i*2
    hap1<-hap2-1
    #MOSAIC ancestries are stored in n_ancestries x n_haplotypes x n_snps matrix
    #select dosage of anc1 for all snps in hap1 of indiv i. Round these dosages either to 0 or 1. Do same for anc2 and anc3 but assign them distinct values
    anc1<-round(local_pos[[1]][1,hap1,])
    anc2<-round(local_pos[[1]][2,hap1,]); anc2[anc2==1]<-2
    anc3<-round(local_pos[[1]][3,hap1,]); anc3[anc3==1]<-3
    #create a single numeric vector of ancestry for hap 1
    hap1_ancestries<-ifelse(anc1==1,anc1,ifelse(anc2==2,anc2,anc3))
    hap1_ancestries[hap1_ancestries==0]<-sample(random,1)
    #select dosage of anc1 for all snps in hap2 of indiv i. Round these dosages either to 0 or 1. Do same for anc2 and anc3 but assign them distinct values
    anc1<-round(local_pos[[1]][1,hap2,])
    anc2<-round(local_pos[[1]][2,hap2,]); anc2[anc2==1]<-2
    anc3<-round(local_pos[[1]][3,hap2,]); anc3[anc3==1]<-3
    #create a single numeric vector of ancestry for hap 2
    hap2_ancestries<-ifelse(anc1==1,anc1,ifelse(anc2==2,anc2,anc3))
    hap2_ancestries[hap2_ancestries==0]<-sample(random,1)
    #paste together the two haplotypes into one vector of two character strings
    diploid_anc<-paste(hap1_ancestries,hap2_ancestries, sep = "")
    #flip ancestries to keep things fair with LAMPLD
    diploid_anc<-gsub("32","23",gsub("31","13",gsub("21","12",diploid_anc)))
    #encode each ancestry as a number
    diploid_anc[diploid_anc == "11"] <- 1
    diploid_anc[diploid_anc == "12"] <- 2
    diploid_anc[diploid_anc == "13"] <- 3
    diploid_anc[diploid_anc == "22"] <- 4
    diploid_anc[diploid_anc == "23"] <- 5
    diploid_anc[diploid_anc == "33"] <- 6
    local_df[,i]<-as.numeric(diploid_anc)
    
    #repeat process for results df
    dip_t<-paste(res[,hap1+2],res[,hap2+2],sep="")
    dip_t<-gsub("32","23",gsub("31","13",gsub("21","12",dip_t)))
    dip_t[dip_t == "11"] <- 1
    dip_t[dip_t == "12"] <- 2
    dip_t[dip_t == "13"] <- 3
    dip_t[dip_t == "22"] <- 4
    dip_t[dip_t == "23"] <- 5
    dip_t[dip_t == "33"] <- 6
    dip_t<-as.numeric(dip_t)
    diploid_true[,i]<-dip_t
    hap_cor[hap1]<-cor.test(hap1_ancestries,res[,hap1+2],method="pearson")[[4]]
    hap_cor[hap2]<-cor.test(hap2_ancestries,res[,hap2+2],method="pearson")[[4]]
  }
} else if (args$nancestries ==2){
  random<-c(1,2)
  for ( i in c(1:20)){ 
    cat( i, "/ 20\n")
    hap2<-i*2
    hap1<-hap2-1
    anc1<-round(local_pos[[1]][1,hap1,])
    anc2<-round(local_pos[[1]][2,hap1,]); anc2[anc2==1]<-2
    hap1_ancestries<-ifelse(anc1==1,anc1,anc2)
    hap1_ancestries[hap1_ancestries==0]<-sample(random,1)
    anc1<-round(local_pos[[1]][1,hap2,])
    anc2<-round(local_pos[[1]][2,hap2,]); anc2[anc2==1]<-2
    hap2_ancestries<-ifelse(anc1==1,anc1,anc2)
    hap2_ancestries[hap2_ancestries==0]<-sample(random,1)
    diploid_anc<-paste(hap1_ancestries,hap2_ancestries, sep = "")
    diploid_anc<-gsub("21","12",diploid_anc)
    diploid_anc[diploid_anc == "11"] <- 1
    diploid_anc[diploid_anc == "12"] <- 2
    diploid_anc[diploid_anc == "22"] <- 3
    local_df[,i]<-as.numeric(diploid_anc)
    
    dip_t<-paste(res[,hap1+2],res[,hap2+2],sep="")
    dip_t<-gsub("21","12",dip_t)
    dip_t[dip_t == "11"] <- 1
    dip_t[dip_t == "12"] <- 2
    dip_t[dip_t == "22"] <- 3
    diploid_true[,i]<-as.numeric(dip_t)
    
    hap_cor[hap1]<-cor.test(hap1_ancestries,res[,hap1+2],method="pearson")[[4]]
    hap_cor[hap2]<-cor.test(hap2_ancestries,res[,hap2+2],method="pearson")[[4]]
  }
}
hap_cor[is.na(hap_cor)]<-1.01
fwrite(as.list(hap_cor),args$out %&% "_hap_accuracy.txt", sep ="\t", col.names = F)
## assign snp ids to MOSAIC
local_df<-as.data.frame(cbind.data.frame(bim,local_df))
#colnames(local_df)<-c("chm","pos",ids)
diploid_true<-as.data.frame(cbind.data.frame(bim,diploid_true))
##read in known ancestry, make sure it has only the right snp, and cols in the right order
#fwrite(local_df)

#sanity check
print("MOS dim:")
dim(local_df)
str(local_df)
print("actual dim")
dim(diploid_true)
str(diploid_true)
# fwrite(diploid_true,"~/software/Local_Ancestry/MOS_test_True.txt", sep = "\t")
# fwrite(local_df,"~/software/Local_Ancestry/MOS_test_estimated.txt", sep = "\t")
#begin corr tests per haplotype
corrs<-c(rep(0,20))
for (i in c(1:20)){
  corrs[i]<-cor.test(local_df[,(i+2)],diploid_true[,(i+2)],method="pearson")[[4]]
  # print(sd(local_df[,(i+2)]))
  # print(sd(diploid_true[,(i+2)]))
}
warnings()
corrs[is.na(corrs)]<-1.01
str(corrs)
#fwrite(local_df,"~/software/Local_Ancestry/Local_DF.txt",col.names = T,sep='\t' )
#process and write to file
corr_R2<-corrs*corrs

print("writing corrs")
fwrite(as.list(corrs),args$out %&% "_dip_accuracy.txt",sep="\t")
print("writing corr R2")
corr_R2<-as.list(corr_R2)
str(corr_R2)
fwrite(corr_R2,args$out %&% "_dip_accuracy.txt",sep="\t",append=T)