#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -o /home/ryan/logs/${PBS_JOBNAME}.o${PBS_JOBID}.log
#PBS -e /home/ryan/logs/${PBS_JOBNAME}.e${PBS_JOBID}.err
#PBS -l walltime=150:00:00
#PBS -l mem=16gb

for i in ASW ACB MXL PUR EVEN BRYC
do
	for j in 1 2 3
	do
	if [ ${i} == "EVEN" ] || [ ${i} == "BRYC" ]
	then
		nanc=3
	else
		nanc=2
	fi
	Rscript ~/software/Local_Ancestry/accuracy_estimation/RFMix_accuracy.R \
	--viterbi ~/ancestry_validation/cohort${j}/thinned/simRFMix/${i}/sim_RFMix/results/${i}.rfmix.2.Viterbi.txt \
	--haps.hap.gz ~/ancestry_validation/cohort${j}/thinned/simRFMix/${i}/sim_RFMix/${i}_merged.haps.hap.gz \
	--haps.sample ~/ancestry_validation/cohort${j}/thinned/simRFMix/${i}/sim_RFMix/${i}_merged.haps.sample \
	--nanc ${nanc} \
	--result ~/ancestry_validation/cohort${j}/original/${i}.result \
	--out ~/ancestry_validation/cohort${j}/thinned/simRFMix/${i}/sim_RFMix/results/RFMIX_${i}_${j}_test 
	done
done
