#!/bin/bash
#PBS -N ELAI_acc
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -o /home/ryan/logs/${PBS_JOBNAME}.o${PBS_JOBID}.log
#PBS -e /home/ryan/logs/${PBS_JOBNAME}.e${PBS_JOBID}.err
#PBS -l walltime=150:00:00
#PBS -l mem=16gb
#for i in BRYC EVEN ASW ACB MXL PUR
for i in ASW MXL PUR ACB
do
	for j in 1 2 3 
	do
		if [ ${i} == "EVEN" ] || [ ${i} == "BRYC" ]
		then
			nanc=3
		else
			nanc=2
		fi
		#rdata=$( ls ~/ancestry_validation/cohort${j}/thinned/simMOSAIC/${i}/MOSAIC_RESULTS/localanc_${i}_${nanc}way*RData )
		#echo $rdata
		echo $nanc
		Rscript ~/software/Local_Ancestry/accuracy_estimation/ELAI_accuracy.R \
		--ps.21 ~/ancestry_validation/cohort${j}/thinned/simELAI/${i}/${i}_${j}_two_way.ps.21.txt \
		--haps.sample ~/ancestry_validation/cohort${j}/thinned/simMOSAIC/${i}/intermediate/${i}.haps.sample \
		--nancestries ${nanc} \
		--result ~/ancestry_validation/cohort${j}/original/${i}.result \
		--pos ~/ancestry_validation/cohort${j}/thinned/simELAI/${i}/${i}_${j}_two_way.recode.pos.txt \
		--out ~/ancestry_validation/cohort${j}/thinned/simELAI/${i}/${i}${j}_
	done
done
