#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -o /home/ryan/logs/${PBS_JOBNAME}.o${PBS_JOBID}.log
#PBS -e /home/ryan/logs/${PBS_JOBNAME}.e${PBS_JOBID}.err
#PBS -l walltime=150:00:00
#PBS -l mem=16gb

for i in ASW
do
	for j in 3
	do
	if [ ${i} == "EVEN" ] || [ ${i} == "BRYC" ]
	then
		nanc=3
	else
		nanc=2
	fi
	Rscript ~/software/Local_Ancestry/accuracy_estimation/LOTER_accuracy.R \
	--loter ~/data/ancestry_validation/cohort${j}/thinned/simLoter/${i}/${i}_phase_corrected_results.txt \
	--poslist ~/data/ancestry_validation/cohort${j}/thinned/${i}_thinning_thinned_pos \
	--ref.map ~/data/ancestry_validation/cohort${j}/original/${i}.ref.map \
	--nanc ${nanc} \
	--result ~/data/ancestry_validation/cohort${j}/original/${i}.result \
	--out ~/software/Local_Ancestry/accuracy_estimation/results/${i}_${j}_loter_phase_corrected.pearson.txt
#	--out ~/ancestry_validation/cohort${j}/thinned/simRFMix/${i}/sim_RFMix/results/RFMIX_${i}_${j}_test 
	done
done
